<XCameraIconButton>
    icon_color: (0, 0, 0, 1)
    _down_color: 1,1,1,1
    icon_size: dp(50)
    canvas.before:
        Color:
            rgba: self.icon_color if self.state == 'normal' else self._down_color
        Ellipse:
            pos: self.pos
            size: self.size
    size_hint: None, None
    size: self.icon_size, self.icon_size
    font_size: self.icon_size/2

<XCamera>:
    pos_hint:{"center_x":.5,"center_y":.5}
    icon: u"[font=data/icons.ttf]\ue800[/font]"
    icon_color: (0.13, 0.58, 0.95, 0.8)
    id: camera
    resolution: 1920, 1080
    allow_stretch: True
    icon: u"[font=data/icons.ttf]\ue800[/font]"
    icon_size: dp(70)
    # size_hint:.5,.5
    XCameraIconButton:
        id: shoot_button
        markup: True
        text: root.icon
        icon_color: root.icon_color
        icon_size: root.icon_size
        on_release: root.shoot()
        right: root.width - dp(5)
        center_y: root.center_y

    # Button:
    #     size_hint:None,None
    #     size:dp(200),dp(30)
    #     text:"back"
    #     center_x: root.center_x
    #     y:root.y+dp(5)
    #     on_release:root.dispatch("on_back")
    # BtnImg:
    #     on_release:root.dispatch("on_back")
    #     markup: True
    #     text: root.icon
    #     icon_color: root.icon_color
    #     icon_size: root.icon_size
    #     on_release: root.shoot()
    #     right: root.width - dp(10)
    #     center_y: root.center_y

        
<LCamera>:
    pos_hint:{"center_x":.5,"center_y":.5}
    resolution: 1920, 1080
    Button:
        background_color:0,0,0,0
        pos_hint:{"center_x":.5,"center_y":.5}
    Image
        pos_hint:{"center_x":.5,"center_y":.5}
        id:img
    # Button:
    #     size_hint:None,None
    #     size:dp(200),dp(30)
    #     text:"back"
    #     center_x: root.center_x
    #     y:root.y+dp(5)
    #     on_release:root.dispatch("on_back")
    