<TgColor@ToggleButton>:
    font_size:self.height/2
    background_color:0,0,0,0
    color:0,0,0,1
    clr:[1,1,1]
    alpa:[.1]
    bold:True
    canvas.before:
        Color:
            rgba:self.clr+self.alpa
        Rectangle:
            size:self.size
            pos:self.pos
    on_state:
        self.alpa=[1]if self.state=="down" else [.1]
<Sc2>:
    pos_hint:{"center_x":.5,"center_y":.5}
    BoxVer:
        spacing:5
        padding:dp(10),0,dp(10),0
        ScreenTittle:
            text:"PLATE SETTING"
            size_hint:1,.06
        FloatLayout
            BoxVer:
                size_hint:1,.2
                pos_hint:{'center_x':.5,"top":1}
                Label:
                    text:"FLOUROPHORES"
                    font_size:self.height/2
                    color:1,1,0,1
                    bold:True
                BoxLayout:
                    TgColor
                        clr:[69.3/100,100/100,8.6/100]
                        text:"FAM"
                        state: 
                            "normal" if root.plate[0]==0 else "down"
                        on_state:
                            root.plate[0]=1 if self.state=="down" else 0
                    TgColor
                        clr:[84.7/100,63.5/100,.4/100]
                        text:"ROX"
                        state: 
                            "normal" if root.plate[1]==0 else "down"
                        on_state:
                            root.plate[1]=1 if self.state=="down" else 0
                    TgColor
                        clr:[100/100,0/100,0/100]
                        text:"Cy5"
                        state: 
                            "normal" if root.plate[2]==0 else "down"
                        on_state:
                            root.plate[2]=1 if self.state=="down" else 0
                    TgColor
                        clr:[100/100,40/100,0/100]
                        text:"CalRed"
                        state: 
                            "normal" if root.plate[3]==0 else "down"
                        on_state:
                            root.plate[3]=1 if self.state=="down" else 0
                    TgColor
                        clr:[100/100,100/100,0/100]
                        text:"HEX"
                        state: 
                            "normal" if root.plate[4]==0 else "down"
                        on_state:
                            root.plate[4]=1 if self.state=="down" else 0
        BoxLayout
            size_hint:1,.1
            spacing:dp(25)
            padding:0,dp(5),0,dp(5)
            BtnLg
                text:"SAVE"
                on_release:
                    pop_save.ilang=.5
            BtnLg
                text:"LOAD"
                on_release:
                    pop_load.ilang=.5
            Label
            BtnLg
                text:"SET"
                on_release:
                    root.dispatch("on_set")
    FloatLayout:
        ilang:10
        id:pop_save
        pos_hint:{"center_x":.5,"center_y":self.ilang}

        Button
            background_color:0,0,0,.9
            pos_hint:{"center_x":.5,"center_y":.5}
            on_press:self.parent.ilang=10
        BoxVer:
            canvas:
                Color:
                    rgba:0,0,1,1
                Rectangle:
                    size:self.size
                    pos:self.pos
            size_hint:.5,.5
            pos_hint:{"center_x":.5,"center_y":.5}
            Button:
                background_color:0,0,0,0
                text:"SAVE PROTOKOL"
                bold:True
                color:0,0,0,1
                font_size:self.height/1.5
                size_hint:1,.2
            GridLayout
                id:gridsave
                spacing:dp(2)
                padding:dp(5)
                cols:3
                BtnGrid
                    id:slot1
                    text:"1"
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10
                BtnGrid
                    id:slot2
                    text:"2"
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10
                BtnGrid
                    text:"3"
                    id:slot3
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10
                BtnGrid
                    text:"4"
                    id:slot4
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10
                BtnGrid
                    text:"5"
                    id:slot5
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10
                BtnGrid
                    id:slot6
                    text:"6"
                    on_release:
                        root.save(self.text)
                        pop_save.ilang=10


    FloatLayout:
        ilang:10
        id:pop_load
        pos_hint:{"center_x":.5,"center_y":self.ilang}
        Button
            background_color:0,0,0,.9
            pos_hint:{"center_x":.5,"center_y":.5}
            on_press:self.parent.ilang=10
        BoxVer:
            canvas:
                Color:
                    rgba:0,0,1,1
                Rectangle:
                    size:self.size
                    pos:self.pos
            size_hint:.5,.5
            pos_hint:{"center_x":.5,"center_y":.5}
            Button:
                background_color:0,0,0,0
                text:"LOAD PROTOKOL"
                bold:True
                color:0,0,0,1
                font_size:self.height/1.5
                size_hint:1,.2
            GridLayout
                spacing:dp(2)
                padding:dp(5)
                cols:3
                BtnGridL
                    alpa:slot1.alpa
                    text:"1"
                    on_release:
                        
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                    
                BtnGridL
                    alpa:slot2.alpa
                    text:"2"
                    on_release:
                        
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                    
                BtnGridL
                    alpa:slot3.alpa
                    text:"3"
                    on_release:
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                BtnGridL
                    alpa:slot4.alpa
                    text:"4"
                    on_release:
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                    
                BtnGridL
                    alpa:slot5.alpa
                    text:"5"
                    on_release:
                        
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                    
                BtnGridL
                    alpa:slot6.alpa
                    text:"6"
                    on_release:
                        
                        root.load(self.alpa,self.text)
                        pop_load.ilang=10
                

        
