#:import utils kivy.utils
<LAbelDisp@BoxVer>:
    unit:""
    canvas:
        Color:
            rgba:0,1,1,.5
        Rectangle:
            size:self.size
            pos:self.pos
    name:""
    value:""
    Label
        color:1,1,0,1
        text:root.name
        size_hint:1,.5
        font_size:self.height/1.3
        bold:True
        font_name:"fonts/batmfa.ttf"
    FloatLayout
        Label
            pos_hint:{"center_x":.5,"center_y":.5}
            color:0,0,0,1
            text:root.value
            font_size:self.height/1
        Label
            pos_hint:{"center_x":.5,"center_y":.5}
            color:0,0,0,1
            text:root.unit
            markup:True
            font_size:self.height/1
        

        # font_name:"fonts/bebas.ttf"
        

<TgStart@ToggleButton>
    background_color:0,0,0,0
    color:0,0,0,1
    warna:0,1,1,.6
    font_size:self.height/2
    font_name:"fonts/batmfa.ttf"
    canvas.before:
        Color:
            rgba:root.warna
        Rectangle:
            size:self.size
            pos:self.pos
    on_state:
        self.text="CANCEL" if self.state=="down" else "START"
        root.warna=[0,1,1,.3] if self.state=="down" else [0,1,1,.6]
        
<PlateClr@Label>:
    color:0,0,0,1
    bold:True
    font_size:self.height/3
    warna:[0,0,0]
    alpa:[.1]
    canvas.before:
        Color:
            rgba:root.warna+root.alpa
        Rectangle:
            size:self.size
            pos:self.pos
<Progress@BoxVer>:
    name:"RT"
    max:100
    value:0
    value2:0
    unit1:"celcius"
    unit2:"menit"
    FloatLayout
        Widget:
            pos_hint:{'center_x':.5,"center_y":.5}
            canvas:
                Color:
                    rgba:1,1,1,.2
                Rectangle:
                    size:self.size
                    pos:self.pos
                Color:
                    rgba:1,1,1,.5
                Rectangle:
                    size:self.size[0],self.size[1]/root.max*root.value
                    pos:self.pos
        BoxVer
            size_hint:1,.09
            pos_hint:{'center_x':.5,"y":1/root.max*root.value}
            Label:
                text:"{:.0f} [sup]o[/sup]C".format(root.value)
                markup:True
                font_size:self.height/1.2
                color:0,0,0,1
            BoxLayout:
                Image:
                    source:"img/panahkiri.png"
                    color:0,0,0,1
                Label:
                    text:"{:.0f} {}".format(root.value2,root.unit2)
                    size_hint:1.5,1
                    font_size:self.height/1.2
                    color:0,0,0,1
                Image:
                    source:"img/panahkanan.png"
                    color:0,0,0,1
    Label:
        text:root.name
        size_hint:1,.06
        color:1,1,0,1
        font_size:self.height/1.5
        bold:True
<Home>:
    size_hint:.975,1
    pos_hint:{"right":.99,"center_y":.5}
    num_prot:0
    num_plate:0
    btn_plate_release:0
    btn_protokol_release:0
    BoxVer:
        BoxLayout:
            size_hint:1,.06
            spacing:dp(2)
            ScreenTittle
                text:"RUN DETAIL"
                size_hint:1,1
                halign:"center"
            BoxLayout
                padding:0,dp(2),0,0
                size_hint:.4,1
                spacing:dp(2)
                
        BoxLayout:
            spacing:dp(10)
            BoxVer:
                padding:dp(5),dp(0),dp(5),dp(0)
                canvas:
                    Color:
                        rgba:0,0,0,1
                    Line:
                        width:dp(1)
                        rectangle:self.x,self.y,self.width,self.height
                        
                Label:
                    size_hint:1,.1
                    font_size:self.height/1.2
                    color:0,0,0,1
                
                BoxLayout  
                    spacing:dp(1)
                    Progress
                        name:"RT"
                        max:100
                        value:root.protokol[0]
                        value2:root.protokol[1]
                    Progress
                        name:"PREDENAT"
                        max:100
                        value:root.protokol[2]
                        value2:root.protokol[3]
                    Progress
                        name:"DENAT"
                        max:100
                        unit2:"second"
                        value:root.protokol[4]
                        value2:root.protokol[5]
                    Progress
                        name:"ANNEAL"
                        max:100
                        unit2:"second"
                        value:root.protokol[6]
                        value2:root.protokol[7]
            
            ScrollView:
                size_hint:.4,1
                id:sv
                BoxVer:
                    size_hint:1,None
                    height:self.minimum_height
                    spacing:dp(5)
                    LAbelDisp:
                        name:"TIMER"
                        value:root.waktu
                        size_hint:1,None
                        height:sv.height/8
                    LAbelDisp:
                        name:"TEMP"
                        value:"{}".format(root.temp)
                        size_hint:1,None
                        height:sv.height/8
                        unit:"               [sup]o[/sup]c"
                    LAbelDisp:
                        name:"CYCLES"
                        value:"{}".format(root.cycles)
                        size_hint:1,None
                        height:sv.height/8
                        unit:"               [sub]times[/sub]"
                    
             
            
        BoxLayout
            size_hint:1,.1
            spacing:dp(10)
            BoxLayout:
                spacing:dp(20)
                padding:0,dp(5),0,dp(5)
                
                BtnLg             
                    text:"PROTOKOL"
                    on_release:
                        root.play_sound()
                        root.parent.current="sc1"
                BtnLg             
                    
                    text:"PLATE"
                    on_release:
                        root.play_sound()
                        root.parent.current="sc2"
                        
            BoxLayout
                padding:0,dp(5),0,dp(5)
                size_hint:.4,1
                TgStart:
                    text:"START"
                    on_state:
                        root.play_sound()
                        root.state=1 if self.state=="down" else 0
