#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition

<BtnLg@Btn>:        
    color:0,0,0,1
    font_size:self.height/2
    font_name:"fonts/batmfa.ttf"
    canvas.before:
        Color:
            rgba:0,1,1,.5
        Rectangle:
            size:self.size
            pos:self.pos

<BoxVer@BoxLayout>:
    orientation:"vertical"
<ScreenTittle@Label>:
    text:"SET PROTOKOL"
    bold:True
    color:0,0,0,1
    size_hint:1,.06
    font_size:self.height/1.5
    halign:"left"
    valign:"middle"
    text_size:self.size
<Ml>:
    bg_color:1,1,1,.8
    # Image
        # size_hint:.3,1
        # source:"img/kawur.png"
    # Camera:
    #     play:True
    # XCamera1
    #     id:cam
        # pos_hint:{"x":-.1,"center_y":.5}
    FloatLayout:
        id:root_cam

    NavigationDrawer:
        id:nd
        BoxVer
        FloatLayout
            canvas.before:
                Color:
                    rgba:root.bg_color
                Rectangle:
                    size:self.size
                    pos:self.pos
                    source:"img/6880.jpg"
            BoxVer:
                pos_hint:{"center_x":.5,"center_y":.5}
                TopNav
                    on_menu_release:nd.toggle_state(True)
                ScreenManager:
                    id:sm
                    transition:SlideTransition(duration=.1)
                    Home:
                        
                        name:"home"
                        protokol:root.protokol
                        plate:root.plate
                        on_setting_cam:
                            root.bg_color=[0,0,0,0]
                            sm.current="sc3"
                        on_step_run:root.on_step_run(self.step)
                    Sc1:
                        name:"sc1"
                        on_set:
                            sm.current="home"
                            root.set_protokol(self.param)
                    Sc2:
                        name:"sc2"
                        on_set:
                            sm.current="home"
                            root.set_plate(self.list_plate)
                        
                    Sc3:
                        name:"sc3"
                        
                        BtnLg:
                            pos_hint:{"x":0,"y":0}
                            size_hint:.2,.1
                            text:"back"
                            on_press:
                                root.bg_color=[1,1,1,.8]
                                sm.current="home"
                                         
                    



                    
                
                

                
            