#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition

<BtnLg@Btn>:        
    color:0,0,0,1
    font_size:self.height/2
    canvas.before:
        Color:
            rgba:0,1,1,.5
        Rectangle:
            size:self.size
            pos:self.pos

<BoxVer@BoxLayout>:
    orientation:"vertical"
<ScreenTittle@Label>:
    text:"SET PROTOKOL"
    bold:True
    color:0,0,0,1
    size_hint:1,.06
    font_size:self.height/1.5
    halign:"left"
    valign:"middle"
    text_size:self.size
<Ml>:
    canvas.before:
        Color:
            rgba:0,1,1,.9
        Rectangle:
            size:self.size
            pos:self.pos
            source:"img/6880.jpg"
    BoxVer:
        TopNav
        ScreenManager:
            id:sm
            transition:SlideTransition(duration=.1)
            Home:
                name:"home"
                protokol:root.protokol
                plate:root.plate
                
            Sc1:
                name:"sc1"
                on_set:
                    sm.current="home"
                    root.set_protokol(self.param)
            Sc2:
                name:"sc2"
                on_set:
                    sm.current="home"
                    root.set_plate(self.list_plate)
            
            
            
            
            



            
            
            

            
            