<Ml>:
    
    NavigationDrawer
        id:nd
        anim_type:"slide_above_simple"
        Button
        FloatLayout
            canvas.before:
                Color:
                    rgba:0,1,1,.8
                Rectangle:
                    size:self.size
                    pos:self.pos
                    source:"img/6880.jpg"
                    # source:"img/yellow.jpg"
                    
            
            BoxVer:
                pos_hint:{"center_x":.5,"center_y":.5}
                TopNav
                    on_menu_release:nd.toggle_state(True)
                ScreenManager:
                    id:sm
                    Screen
                        name:"home"
                        BoxVer:
                            padding:dp(10),0,dp(10),0
                            ScreenTittle
                                text:"RUN DETAIL"
                                size_hint:1,.06
                            BoxLayout:
                                spacing:dp(10)
                                BoxVer:
                                    padding:dp(5),dp(0),dp(5),dp(5)
                                    canvas:
                                        Color:
                                            rgba:0,0,0,1
                                        Line:
                                            width:dp(1)
                                            rectangle:self.x,self.y,self.width,self.height
                                        Color:
                                            rgba:0,0,0,.05
                                        Rectangle:
                                            size:self.size
                                            pos:self.pos
                                    Widget:
                                        size_hint:1,.1
                                    BoxLayout  
                                        spacing:dp(3)
                                        id:root_step
                                        Progress
                                            name:"RT"
                                            max:100
                                            value:root.protokol[0]
                                            value2:root.protokol[1]
                                        Progress
                                            name:"PREDENAT"
                                            max:100
                                            value:root.protokol[2]
                                            value2:root.protokol[3]
                                        Progress
                                            name:"DENAT"
                                            max:100
                                            unit2:"detik"
                                            value:root.protokol[4]
                                            value2:root.protokol[5]
                                        Progress
                                            name:"ANNEAL"
                                            max:100
                                            unit2:"detik"
                                            value:root.protokol[6]
                                            value2:root.protokol[7]
                                ScrollView:
                                    size_hint:.4,1
                                    id:sv
                                    BoxVer:
                                        size_hint:1,None
                                        height:self.minimum_height
                                        spacing:dp(5)
                                        LAbelDisp:
                                            name:"TIMER"
                                            value:"{:02d}:{:02d}:{:02d}".format(root.jam,root.menit,root.detik)
                                            size_hint:1,None
                                            height:sv.height/8
                                        LAbelDisp:
                                            name:"TEMP"
                                            value:"{:.1f}".format(root.temp)
                                            size_hint:1,None
                                            height:sv.height/8
                                            unit:"               [sup]o[/sup]c"
                                        LAbelDisp:
                                            name:"CYCLES"
                                            value:"{}".format(root.cycles)
                                            size_hint:1,None
                                            height:sv.height/8
                                            unit:"               [sub]times[/sub]"
                            BoxLayout
                                size_hint:1,.1
                                spacing:dp(10)
                                padding:0,dp(5),0,dp(5)
                                BtnLg             
                                    text:"SET CAMERA"
                                    on_release:sc_cam.ilang=.5
                                BtnLg             
                                    text:"PROTOKOL"
                                    on_release:
                                        sm.current="protokol_settings"
                                BtnLg             
                                    text:"PLATE"
                                    on_release:
                                        sm.current="plate_settings"
                                TgStart:
                                    text:"START"
                                    size_hint:1.23,1
                                    on_state:
                                        root.state=1 if self.state=="down" else 0
                    Sc1
                        name:"protokol_settings"
                        on_set:
                            sm.current="home"
                            root.protokol=self.protokol
                    Sc2
                        name:"plate_settings"
                        on_set:
                            sm.current="home"
                            root.plate=self.plate                            

                    


    FloatLayout
        id:sc_cam
        ilang:10
        pos_hint:{"center_x":.5,"center_y":self.ilang}
        # BoxLayout
        #     id:root_cam
        #     pos_hint:{"center_x":.5,"center_y":.5}
        XCamera
            pos_hint:{"center_x":.5,"center_y":.5}
            size_hint:None,None
            size:1920,1080
            on_texture:root.print_cam(self)
            id:cam
            on_warna:
                root.set_warna(self.warna,self.texture.size)

        BtnLg:
            size_hint:.2,.08
            text:"back"
            on_release:sc_cam.ilang=10
            pos_hint:{"x":.5,"y":0}
        Widget:
            pos_hint:{"center_x":.5,"center_y":.5}
            size_hint:None,None
            id:line
            warna:1,1,1,1
            canvas:
                Color:
                    rgba:1,1,1,1
                Line:
                    width:dp(2)
                    rectangle:(self.x,self.y,self.width,self.height)
        Widget:
            warna:1,1,1,1
            pos_hint:{"center_x":.5,"center_y":.5}
            size_hint:None,None
            id:bunder
            size:min(root.size)/10,min(root.size)/10
            canvas:
                Color:
                    rgba:self.warna
                Ellipse:
                    size:self.size
                    pos:self.pos
        Label:
            pos_hint:{"center_x":.5,"y":.1}
            font_size:self.height/10
            color:0,1,0,1
            id:lbl_clr

            
    



            
